name: Python updated argument check

on:
  push:
    branches:
      - main
      - dev

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set working directory
      run: cd ${{ github.workspace }}/auxiliary

    - name: Run Python script
      run: python ${{ github.workspace }}/auxiliary/arg_checks.py
